OUT_AudioPath = "Resources/Audio/"
OUT_CompressedPath = "Resources/Compressed/"
OUT_DocumentsPath = "Resources/Documents/"
OUT_ImagePath = "Resources/Image/"
OUT_VideoPath = "Resources/Video/"

RES_AudioPath = "Outputs/Audio/"
RES_CompressedPath = "Outputs/Compressed/"
RES_DocumentsPath = "Outputs/Documents/"
RES_ImagePath = "Outputs/Image/"
RES_VideoPath = "Outputs/Video/"